name: "ioBroker Soundcraft"
version: "0.1.0"
slug: "iobroker_soundcraft"
description: "ioBroker with Soundcraft Ui12 support"
url: "https://github.com/roypa-dxb/ha-soundcraft-ui12"

arch:
  - amd64
  - aarch64

startup: services
boot: auto
init: false

image: "iobroker/iobroker"

ports:
  8081/tcp: 8081

ports_description:
  8081/tcp: "ioBroker Admin Interface"

webui: "http://[HOST]:[PORT:8081]"

map:
  - type: data
    read_only: false

options:
  timezone: "Asia/Dubai"

schema:
  timezone: str
